// resources/js/Components/Tarocchi/Carta/Carta.jsx
import React from 'react'

export default function Carta({isCoperta=false,num, height}) {

  const [imgUrl, setImgUrl] = React.useState(isCoperta?"/images/dorso.jpg":"/images/"+num+".jpg") ;


  return (
    <div style={{height:height}}>
        
            <img style={{height:"100%"}} src={imgUrl}></img>
        
    </div>
  )
}

// resources/js/Pages/Carta.svelte
<script>
    export let num;
    export let height="100px";
    export let isFaceDown=false;

    let imgUrl;

    if(isFaceDown)
        imgUrl="/images/dorso.jpg"
    else
        imgUrl="/images/"+num+".jpg"
    

</script>




<div style="height:{height};">

    <img style='height:100%' src={imgUrl} alt="carta"/>

</div>
